language: python
python:
  - '3.7'
matrix:
  include:
    - python: '3.7'
      dist: xenial
      sudo: true
env:
  global:
    - BOTO_CONFIG=/dev/null # https://github.com/spulec/moto/issues/1771
install:
  - pip install -r requirements/test.txt
script:
  - pytest --cov-report=xml --cov=extractor
  - flake8
  - pylint **/*.py
after_success:
  - codecov
before_deploy:
  - pip install -t lib/ -r requirements/base.txt
deploy:
  provider: lambda
  function_name: tank-level-extractor
  region: us-east-1
  role: arn:aws:iam::980858071036:role/lambda-tank-levels
  runtime: python3.7
  module_name: extractor/extractor
  handler_name: lambda_handler
  environment_variables:
    - PYTHONPATH=lib
    - TRANSFORMER_ARN='arn:aws:sns:us-east-1:980858071036:tank-level-email'
