language: python
python:
  - '3.6'
install:
  - pip install -r requirements/test.txt
script:
  - pytest --cov=extractor
  - flake8
  - pylint **/*.py
after_success:
  - codecov
deploy:
  provider: lambda
  function_name: tank-level-extractor
  region: us-east-1
  role: arn:aws:iam::980858071036:role/service-role/tank-levels
  runtime: python3.6
  module_name: extractor/extractor
  handler_name: extract
