version: 0.2

env:
  variables:
    CODECOV_TOKEN: 52974e58-752e-4e69-899d-08d6f39baadc

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements/test.txt
      - pip install -t lib/ -r requirements/base.txt  # this is for deployment
  build:
    commands:
      - echo Build started on `date`
        - flake8
        - pylint **/*.py
        - pytest --cov-report=xml --cov=extractor
  post_build:
    commands:
      - codecov
      - echo Build completed on `date`
