version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements/test.txt
  build:
    commands:
      - echo Build started on `date`
      - flake8
      - pylint **/*.py
      - pytest --cov-report=xml --cov=extractor
  post_build:
    commands:
      - codecov
      - pip install -t lib/ -r requirements/base.txt
      - echo Build completed on `date`
